version: '3'

vars:
  BINARY: bin/banner_rotation
  API: api
  CONFIG: configs/config.yaml
  MIGRATIONS: migrations
  DB: postgres
  DSN: host=localhost user=danny password=danny dbname=rotation sslmode=disable

tasks:
  default:
    - task: build

  build:
    desc: Build the go binary
    cmds:
      - go build -v -o {{.BINARY}} ./cmd

  run:
    desc: Run the banner_rotation service with default config(from configs directory)
    deps: [ build ]
    cmds:
      - ./{{.BINARY}} --config={{.CONFIG}}

  clean:
    desc: Clean binary directory
    cmds:
      - rm -rf bin

  lint:
    desc: Lint project
    cmds:
      - task: install-lint-deps 
      - golangci-lint run ./...

  install-lint-deps:
    desc: Intall lint dependencies
    cmds:
      - (which golangci-lint > /dev/null) || curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.41.1

  test:
    desc: Run test with race detector
    cmds:
      - go test -race -count 100 ./...

  generate:
    desc: Generate all requried for project build codegenerated sources
    cmds:
      - go generate -x ./...

  migrate_up:
    desc: Apply all migrations from migrations dir
    cmds:
      - goose -dir {{.MIGRATIONS}} {{.DB}} "{{.DSN}}" up

  migrate_down:
    desc: Rollback all migrations from migrations dir
    cmds:
      - goose -dir {{.MIGRATIONS}} {{.DB}} "{{.DSN}}" down

  evans:
    desc: Start evans grpc (https://github.com/ktr0731/evans) client
    cmds:
      - evans {{.API}}/*.proto --port=56789