logger:
  level: info
  file: ./rotation_logs.log
db:
  maxOpenConnections: 20
  maxIdleConnections: 5
  # connection lifetime in minutes
  maxConnectionLifetime: 3m
  dsn: "host=localhost user=danny password=danny dbname=rotation sslmode=disable"
server:
  host: localhost
  port: 50051
  # connection timeout in seconds
  connectionTimeout: 5s