logger:
  level: info
  file: ./rotation_logs.log
db:
  maxOpenConnections: 20
  maxIdleConnections: 5
  maxConnectionLifetime: 3m
  dsn: "host=net-db user=danny password=danny dbname=rotation sslmode=disable"
server:
  host: net-rotation
  port: 50051
  connectionTimeout: 5s