name: Banner rotation service CI

on:
  push:
    branches:
      - main
  pull_request:


env:
  GO111MODULE: "on"

jobs:
  tasks_with_tasklist:
    runs-on: ubuntu-20.04
    steps:
      
      - name: Install Task
        uses: arduino/setup-task@v1
    
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out code
        uses: actions/checkout@v2

      - name: Task lint
        run: task lint -- --timeout 5m

      - name: Task test
        run: task test

      - name: Task build
        run: task build
